# Generated by Django 4.1.4 on 2024-05-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0070_remove_message_receiver_remove_message_sender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerGuidanceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_guidance_messages",
                        to="app.course",
                    ),
                ),
            ],
        ),
    ]
