# Generated by Django 5.0.6 on 2024-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0073_blogpost_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
