# Generated by Django 5.0.6 on 2024-06-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0078_remove_discussion_user_discussion_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
