# Generated by Django 5.0.6 on 2024-06-05 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0081_mentorshiprequest_delete_reply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mentorship",
        ),
    ]
