# Generated by Django 5.0.6 on 2024-06-05 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0082_delete_mentorship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MentorshipRequest",
        ),
    ]
