# Generated by Django 5.0.6 on 2024-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0087_mentorshiprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="type",
            field=models.CharField(default="common", max_length=20),
        ),
    ]
