# Generated by Django 5.0.6 on 2024-06-25 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0088_discussion_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discussion",
            name="type",
        ),
    ]
