# Generated by Django 5.0.6 on 2024-06-27 15:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0092_weekcomment_weekpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weekpost",
            name="week",
        ),
        migrations.AddField(
            model_name="weekpost",
            name="week_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=app.models.Week
            ),
        ),
        migrations.DeleteModel(
            name="WeekComment",
        ),
    ]
