# Generated by Django 5.0.6 on 2024-06-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0093_remove_weekpost_week_weekpost_week_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.student",
                    ),
                ),
                (
                    "week_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.weekpost"
                    ),
                ),
            ],
        ),
    ]
