# Generated by Django 5.0.6 on 2024-07-23 14:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0094_weekcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerguidancemessage",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
