# Generated by Django 5.0.6 on 2024-07-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0095_alter_careerguidancemessage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Course Content"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Instructor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="requirement",
            field=models.TextField(blank=True, null=True, verbose_name="Requirement"),
        ),
    ]
