# Generated by Django 5.0.6 on 2024-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0096_course_course_content_course_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="Full_Name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
