# Generated by Django 5.0.6 on 2024-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0098_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="staticfiles/bundle_images/"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "courses",
                    models.ManyToManyField(related_name="bundles", to="app.course"),
                ),
            ],
        ),
    ]
